version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: builtattic_mongo
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]
  redis:
    image: redis:7
    container_name: builtattic_redis
    ports: ["6379:6379"]
  api:
    build: .
    container_name: builtattic_api
    ports: ["3000:3000"]
    volumes:
      - .:/app
      - /app/node_modules
    depends_on: [mongo, redis]
volumes:
  mongo_data:
